development:
  adapter: postgresql
  database: error_tracker_development
  pool: 5
  host: localhost
  timeout: 5000

test:
  adapter: postgresql
  database: error_tracker_test
  pool: 5
  host: localhost
  timeout: 5000

production:
  adapter: postgresql
  database: error_tracker_production
  pool: 5
  host: localhost
  timeout: 5000
